name: Publish
on:
  push:
    branches:
      - master

jobs:
  Lint_and_Test:
    name: Lint_and_Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

  Build_Release_and_Deploy:
    name: Build_Release_and_Deploy
    runs-on: ubuntu-latest
    needs: Lint_and_Test
    strategy:
      matrix:
        node: [ 18 ]
    steps:
      - name: Build
        run: |
          npm ci
          npm run build
          npm run package

      - name: Create Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}